### ISSUE TITLE
convert Tensorflow weights to Pytorch weights 

### ISSUE THREAD

**Issue by xbpgithub** [zsef123/EfficientNets-PyTorch#4]
I have converted Tensorflow weights to Pytorch weights perfectly using your code in EfficientNet-b0, but I got some wrong from EfficientNet-b1 to EfficientNet-b3.
I would like to ask if you have completed the code, and can you help fix these bugs?
Traceback (most recent call last):
  File "convert.py", line 117, in <module>
    convert_MBConv(mbconv, key_to_param(tf_mbconv))
  File "convert.py", line 68, in convert_MBConv
    convert_se(m.se, tf_params[10:14])
  File "convert.py", line 55, in convert_se
    convert_conv(m.se[1], tf_params[0], tf_params[1])
  File "convert.py", line 19, in convert_conv
    m.weight.data = torch.from_numpy(np.transpose(weight, (3, 2, 0, 1)))
  File "/home/xux/anaconda3/envs/tf1.9_py3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/xux/anaconda3/envs/tf1.9_py3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

I download eval_ckpt_main.py and some other files from  Official TF Repo, I don't know if they are necessary.  Can you give me some help?

**Comment by dami23** [comment]
Hi @zsef123 . Thank you for your share. I also encounter the same problem with xbpgithub, "ValueError: axes don't match array". It means your repo only can be used to transfer efficientnet-b0, cannot transfer b1-b5 models to pytorch, right?

**Comment by kacper1095** [comment]
@dami23, @xbpgithub you can follow the original tensorflow [code](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py). On the top  of the file, after imports, there's a dict with params for each `b` network in the form of four elements tuples:
- 1st element = `width_coeff`
- 2nd element = `depth_coeff`
- 3rd element = size of the input image
- 4th element = `dropout_rate`

You can put 1st, 2nd and 4th elements in a constructor in the line #48. The 3rd should be used, for example, when you load the data.

After the params are changed, the code works correctly.

EDIT: Also, channels, where `self.stem` is created, should be wrapped in the method `renew_ch`.
